# Developed by Pratik Mansukhlal #
---
- hosts: puppet

  vars_prompt:
   - name: "confirmation"
     prompt: "Are you sure want to reboot the machine?"
     private: no
  tasks:

# This task will reboot machine only if we give "yes" #
  - name: Rebooting the machine
    command: /sbin/shutdown -r now
    when: confirmation=="yes"

# This pause is mandatory, otherwise the existing control connection gets reused #
  - pause: seconds=60

# It will try to ping server after 60 seconds and tries 30 times untill server gets up #
  - local_action: shell ansible -m ping 192.168.2.26
    register: result
    until: result.rc==0
    retries: 30
    delay: 10

# This will check the uptime of server after reboot #
  - shell: uptime
